
package demo.hw.server.service;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import javax.xml.namespace.QName;
import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 3.5.9
 * 2024-12-03T14:37:00.459+08:00
 * Generated source version: 3.5.9
 */
public final class HelloWorld_HelloWorldImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://service.server.hw.demo/", "HelloWorld");

    private HelloWorld_HelloWorldImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = HelloWorld_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        HelloWorld_Service ss = new HelloWorld_Service(wsdlURL, SERVICE_NAME);
        HelloWorld port = ss.getHelloWorldImplPort();


        System.out.println("Invoking sayHi...");
        java.lang.String _sayHi_arg0 = "HHHHH";
        java.lang.String _sayHi__return = port.sayHi(_sayHi_arg0);
        System.out.println("sayHi.result=" + _sayHi__return);


        System.out.println("Invoking sayHiToUser...");
        demo.hw.server.service.User _sayHiToUser_arg0 = new User();
        _sayHiToUser_arg0.setName("Joe");
        java.lang.String _sayHiToUser__return = port.sayHiToUser(_sayHiToUser_arg0);
        System.out.println("sayHiToUser.result=" + _sayHiToUser__return);

        System.out.println("Invoking getUsers...");
        demo.hw.server.service.IntegerUserMap _getUsers__return = port.getUsers();
        System.out.println("getUsers.result=" + _getUsers__return.getEntry());

        System.out.println("Invoking getUserList...");
        demo.hw.server.service.UserList _getUserList__return = port.getUserList();
        System.out.println("getUserList.result=" + _getUserList__return.getUserList());

        System.exit(0);
    }

}
